### PR TITLE
Add comment for BCM2708_PERI_BASE

### PR DESCRIPTION
**Pull request by normanfeltz**
For the Raspberry Pi 1 use: 0x20000000
For the Raspberry Pi 2 or 3 use: 0x3F000000

### CODE REVIEW

**Comment by danjperron** [comment]
No! no need! 
  setup_io() will check which address the gpio are located from /proc/device-tree/soc/ranges and will set BCM2708_PERI_BASE  to the correct location.


Also with the use of  /dev/gpiomem, the USE_GPIOMEM define flag,  everything is set at  the base 0 address and no need to sudo anymore.

**Comment by normanfeltz** [comment]
Fix! I have a old version on the repo on a fork.

**Comment by clarity-phev** [comment]
Interesting...  I have run the base code on both a Pi-zero and a Pi-3.
Seemed to work for both in my case.

-Tom

**Comment by danjperron** [comment]
Normanfeltz figure it out. He was using my old code.  The new code uses /dev/gpiomem than the base address of the GPIO is not an issue  and also you don't need to sudo anymore!

Even if you toggle off the USE_GPIOMEM  the new code will  figure out what is your base address anyway!

**Pull request closed without merging**
